language: python
os:
  - linux
python:
  - "2.7"
  - "3.5"
jdk:
  - oraclejdk8
before_install:
  - pip install virtualenv
script:
  - pip install coverage
  - pip install nose
  - nosetests --with-coverage --cover-package=tethne
