language: python
os:
  - linux
python:
  - "2.7.9"
  - "2.7.10"
jdk:
  - oraclejdk8
script:
  - pip install coverage
  - pip install nose
  - pip install --pre slate==0.5.2
  - python -m nltk.downloader punkt
  - python -m nltk.downloader stopwords
  - nosetests --with-coverage --cover-package=tethne
