language: python
os:
  - linux
  - osx
python:
  - "2.6"
  - "2.7"
  - "3.5"
jdk:
  - oraclejdk8
script:
  - pip install coverage
  - pip install nose
  - nosetests --with-coverage --cover-package=tethne
