language: python
cache: pip
os:
  - linux
python:
  - "2.7.9"
  - "2.7.10"
jdk:
  - oraclejdk8
script:
  - pip install -U pip
  - pip install coverage
  - pip install nose
  - pip install gensim
  - python -m nltk.downloader punkt
  - python -m nltk.downloader stopwords
  - nosetests --with-coverage --cover-package=tethne
