language: python
os:
  - linux
python:
  - "2.7.9"
  - "2.7.10"
jdk:
  - oraclejdk8
script:
  - pip install coverage
  - pip install nose
  - python -m nltk.downloader all
  - nosetests --with-coverage --cover-package=tethne
